name: Python Tests

on: 
  push:
    branches: 
      - main  # Change this to your default branch if necessary
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest  # The OS on which the workflow will run

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'  # Specify the Python version you want to use

      - name: Create and activate virtual environment
        run: |
          python -m venv myenv
          echo "##[add-path]$(pwd)/myenv/bin"  # Add venv to PATH
          source myenv/bin/activate

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Use requirements.txt for all dependencies

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: myenv/lib/python3.13/site-packages
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Run tests
        run: |
          python -m unittest discover -s test -p "*.py"
